wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713403840.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.6
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.01
max_depth:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 400
