wandb_version: 1

booster:
  desc: null
  value: gbtree
max_depth:
  desc: null
  value: 12
learning_rate:
  desc: null
  value: 0.05
subsample:
  desc: null
  value: 0.3
seed:
  desc: null
  value: 117
test_size:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713401009.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.6
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
